/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.systemjaade.tecladosj;

import com.systemjaade.tecladosj.gui.TecladoAlfabetico;
import com.systemjaade.tecladosj.gui.TecladoNumerico;
import java.awt.Color;
import java.awt.Point;

/**
 * Clase textTest.java
 *
 * @author Tarazona Marrujo Elí Gamaliel - "System JAADE S.A.C."
 * @version 11-mar-2019 8:51:52 SJ
 */
public class textTest extends javax.swing.JFrame {

  private TecladoAlfabetico keyboardAlfabetico;
  private TecladoNumerico keyboardNumerico;

  /**
   * Creates new form textTest
   */
  public textTest() {
    initComponents();
    keyboardAlfabetico = new TecladoAlfabetico();
    keyboardNumerico = new TecladoNumerico();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    txtNombres = new javax.swing.JTextField();
    txtApellidos = new javax.swing.JTextField();
    txtDni = new javax.swing.JTextField();
    txtTelefono = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtSalida = new javax.swing.JTextArea();
    pswRepiteContrasena = new javax.swing.JPasswordField();
    pswContrasena = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    txtNombres.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombres", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    txtNombres.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        txtNombresMouseClicked(evt);
      }
    });
    txtNombres.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNombresActionPerformed(evt);
      }
    });

    txtApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    txtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        txtApellidosMouseClicked(evt);
      }
    });

    txtDni.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    txtDni.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        txtDniMouseClicked(evt);
      }
    });

    txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        txtTelefonoMouseClicked(evt);
      }
    });

    txtSalida.setColumns(20);
    txtSalida.setRows(5);
    txtSalida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    txtSalida.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        txtSalidaMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(txtSalida);

    pswRepiteContrasena.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repite Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    pswRepiteContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        pswRepiteContrasenaMouseClicked(evt);
      }
    });

    pswContrasena.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
    pswContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        pswContrasenaMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(51, 51, 51)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(36, 36, 36)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(pswContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pswRepiteContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(45, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(21, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(31, 31, 31)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(pswRepiteContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(pswContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(24, 24, 24))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed

  }//GEN-LAST:event_txtNombresActionPerformed

  private void txtNombresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombresMouseClicked
    Point p = txtNombres.getLocationOnScreen();
    p.y += 55;
    keyboardAlfabetico.dispose();
    keyboardAlfabetico = new TecladoAlfabetico(txtNombres);
    keyboardAlfabetico.setColorPrimary(Color.MAGENTA);
    keyboardAlfabetico.setColorSecondary(Color.PINK);
    keyboardAlfabetico.setBtnEnterColor(TecladoAlfabetico.ENTER_ALFABETICO_ANARANJADO);
    keyboardAlfabetico.setLocation(p);
    keyboardAlfabetico.setVisible(true);
  }//GEN-LAST:event_txtNombresMouseClicked

  private void txtDniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniMouseClicked
    Point p = txtDni.getLocationOnScreen();
    p.y += 55;
    keyboardNumerico.dispose();
    keyboardNumerico = new TecladoNumerico(txtDni);
    keyboardNumerico.setColorPrimary(Color.RED);
    keyboardNumerico.setColorSecondary(Color.cyan);
    keyboardNumerico.setBtnEnterColor(TecladoNumerico.ENTER_NUMERICO_VERDE);
    keyboardNumerico.setLocation(p);
    keyboardNumerico.setVisible(true);
  }//GEN-LAST:event_txtDniMouseClicked

  private void txtApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosMouseClicked
    Point p = txtApellidos.getLocationOnScreen();
    p.y += 55;
    keyboardAlfabetico.dispose();
    keyboardAlfabetico = new TecladoAlfabetico(txtApellidos);
    keyboardAlfabetico.setColorPrimary(Color.GRAY);
    keyboardAlfabetico.setColorSecondary(Color.BLUE);
    keyboardAlfabetico.setBtnEnterColor(TecladoAlfabetico.ENTER_ALFABETICO_FUCHSIA);
    keyboardAlfabetico.setLocation(p);
    keyboardAlfabetico.setVisible(true);
  }//GEN-LAST:event_txtApellidosMouseClicked

  private void txtTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseClicked
    Point p = txtTelefono.getLocationOnScreen();
    p.y += 55;
    keyboardNumerico.dispose();
    keyboardNumerico = new TecladoNumerico(txtTelefono);
    keyboardNumerico.setColorPrimary(Color.MAGENTA);
    keyboardNumerico.setColorSecondary(Color.ORANGE);
    keyboardNumerico.setBtnEnterColor(TecladoNumerico.ENTER_NUMERICO_ROSA);
    keyboardNumerico.setLocation(p);
    keyboardNumerico.setVisible(true);
  }//GEN-LAST:event_txtTelefonoMouseClicked

  private void pswContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswContrasenaMouseClicked
    Point p = pswContrasena.getLocationOnScreen();
    p.y += 55;
    keyboardAlfabetico.dispose();
    keyboardAlfabetico = new TecladoAlfabetico(pswContrasena);
    keyboardAlfabetico.setColorPrimary(Color.MAGENTA);
    keyboardAlfabetico.setColorSecondary(Color.ORANGE);
    keyboardAlfabetico.setBtnEnterColor(TecladoNumerico.ENTER_NUMERICO_ROSA);
    keyboardAlfabetico.setLocation(p);
    keyboardAlfabetico.setVisible(true);
  }//GEN-LAST:event_pswContrasenaMouseClicked

  private void pswRepiteContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswRepiteContrasenaMouseClicked
    Point p = pswRepiteContrasena.getLocationOnScreen();
    p.y += 55;
    keyboardAlfabetico.dispose();
    keyboardAlfabetico = new TecladoAlfabetico(pswRepiteContrasena);
    keyboardAlfabetico.setColorPrimary(Color.MAGENTA);
    keyboardAlfabetico.setColorSecondary(Color.ORANGE);
    keyboardAlfabetico.setBtnEnterColor(TecladoNumerico.ENTER_NUMERICO_ROSA);
    keyboardAlfabetico.setLocation(p);
    keyboardAlfabetico.setVisible(true);
  }//GEN-LAST:event_pswRepiteContrasenaMouseClicked

  private void txtSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalidaMouseClicked
    Point p = txtSalida.getLocationOnScreen();
    p.y += 55;
    keyboardAlfabetico.dispose();
    keyboardAlfabetico = new TecladoAlfabetico(txtSalida);
    keyboardAlfabetico.setColorPrimary(Color.MAGENTA);
    keyboardAlfabetico.setColorSecondary(Color.ORANGE);
    keyboardAlfabetico.setBtnEnterColor(TecladoNumerico.ENTER_NUMERICO_ROSA);
    keyboardAlfabetico.setLocation(p);
    keyboardAlfabetico.setVisible(true);
  }//GEN-LAST:event_txtSalidaMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(textTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(textTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(textTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(textTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new textTest().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPasswordField pswContrasena;
  private javax.swing.JPasswordField pswRepiteContrasena;
  private javax.swing.JTextField txtApellidos;
  private javax.swing.JTextField txtDni;
  private javax.swing.JTextField txtNombres;
  private javax.swing.JTextArea txtSalida;
  private javax.swing.JTextField txtTelefono;
  // End of variables declaration//GEN-END:variables

}
